### ISSUE TITLE
Issue with ERA5 download data

### ISSUE THREAD

**Issue by lushilima** [trondkr/ERA5-ROMS#1]
Hi Trondkr. I'm using your script to download the ERA5 data to use in my ROMS domain. However, the download is apparently doing very slowly, and after some time the process is killed unexpectedly, at different times (in my failed attempts to download and process the data).  It can be something wrong with the solicitation? do you know if we have a limit of downloads of ERA5 data?

I am trying to download:
- 'reanalysis-era5-single-levels'
- 3hourly data from 1998 to 2018. (10m u,v wind, 2m temperature, mean sea level pressure, mean surface downward long and short wave radiation fluxes, total cloud cover, total precipitation, specific humidity)
- domain: -30/-140/-85/40

The download starts, it is downloaded 1998 u_wind, v_wind, they are converted to ROMS, but it stops when it finishes the 2m-temperature, or before...

**Comment by trondkr** [comment]
@lushilima Hi, I have not had a problem with that and have downloaded very big files. Can you try to run just the 2m temperature and see if it fails? Also, test with a smaller domain to allow this to run much faster. I have downloaded data from the Northern Hemisphere for 20 years for all variables and it took a few days to do so (7 days). 

I should also warn you that I am looking for a bug in my code that prevents ROMS from correctly reading the timestep. The files are read correctly but it seems ROMS keeps reading the first index of the generated ERA5 files. I will work on the bug this week.

**Comment by lushilima** [comment]
Hi @trondkr 
I started to work by parts. 
I downloaded separately and I'm preparing to ROMS right now. And thinking about the issue that you pointed about timestep!
Thanks!!
