### ISSUE TITLE
Bug in ECMWF_tools.py?

### ISSUE THREAD

**Issue by jkansong** [trondkr/ERA5-ROMS#2]
Hi Trond, 
Could you please check whether there's a bug in ECMWF_tools.py. I specified both the start and end dates to be 2015 in ECMWF_querry.py, but when the download completed it started to grab data for 2016. Thanks again for this tool!

Regards,
Joseph K. Ansong

**Comment by trondkr** [comment]
@jkansong 
Thanks for reporting this bug. This has been fixed in the current version.
