### ISSUE TITLE
Problem with using output to run ROMS

### ISSUE THREAD

**Issue by trondkr** [trondkr/ERA5-ROMS#3]
When testing the current output of this package for an Arctic ROMS model it seems that ROMS has either 1) a problem with one of the variables that prevent seasonality to emerge in the ROMS solution 2) the internal interpolation in ROMS is broken.. This needs to be further investigated

**Comment by lushilima** [comment]
Hi Trond, 
I found the same issue, I supose.
When we use ERA5 to run ROMS. 

` Initial domain volumes:  TotVolume =  3.2449563409E+16 m3
                         MinCellVol =  1.1849078930E+07 m3
                         MaxCellVol =  1.4712066248E+11 m3
                            Max/Min =  1.2416210859E+04

 NL ROMS/TOMS: started time-stepping: (Grid: 01 TimeSteps: 000000012097 - 000000038880)

    GET_2DFLD   - surface u-wind component,                        1998-01-15 00:00:00.00
                   (Grid=01, Rec=0000113, Index=2, File: era5_u10_year_1998_roms.nc)
                   (Tmin=      18263.0000 Tmax=      18627.8750)      t =      18277.0000
                   (Min =  1.00000000E+35 Max = -1.00000000E+35)      regrid = T
    GET_2DFLD   - surface v-wind component,                        1998-01-15 00:00:00.00
                   (Grid=01, Rec=0000113, Index=2, File: era5_v10_year_1998_roms.nc)
                   (Tmin=      18263.0000 Tmax=      18627.8750)      t =      18277.0000
                   (Min =  1.00000000E+35 Max = -1.00000000E+35)      regrid = T
    GET_2DFLD   - surface air pressure,                            1998-01-15 00:00:00.00
                   (Grid=01, Rec=0000113, Index=2, File: era5_msl_year_1998_roms.nc)
                   (Tmin=      18263.0000 Tmax=      18627.8750)      t =      18277.0000
                   (Min =  1.00000000E+35 Max = -1.00000000E+35)      regrid = T`


Did you found the same issue, after the first time-step, all the atm data gets crazy?
In the ROMS forum, I realized that someone else also had the same error and also used the ERA5-roms.

**Comment by lushilima** [comment]
Hi Trond, 
I solved the problem that I described above. This happened due the latitude was inverted. And consequently, the model couldn't read the data correctly.

**Comment by trondkr** [comment]
@lushilima Great! Would you mind posting the code for inverting the latitude and where you did this (or do a pull request)? Then I can fix it too. Thanks

**Comment by lushilima** [comment]
Well, I tested this changing the data with NCO... 
So now I am testing and trying to change on the script.
Also, I have changed the time config because my simulations use seconds instead of hours as a pattern.
