### ISSUE TITLE
Regarding location where output file shall be saved

### ISSUE THREAD

**Issue by neelbasak08** [trondkr/ERA5-ROMS#4]
Hello sir,
I am trying to use your script ERA5-ROMS. Thanks a lot for your such a generous contribution. Although I had an issue. After running the toolbox using according to Run the toolbox section of Readme.md file, I am not sure where the file is being saved(i mean its location and filename). May be it's a bug or maybe I am unable to use it in a proper way. Also is there a way that I can use this script to create forcing on my own grid present in netcdf format ?

Thanks a lot for your help in advance @trondkr

**Comment by trondkr** [comment]
@neelbasak08  Sorry for the very late response to your question. In the latest version of the code, you can specify the results directory where all of the files will be stored. Take a look in `ECMWF_query.py` and you should see:

    self.project = "ROHO800"
    self.resultsdir = "../oceanography/ERA5/{}/".format(self.project)

Where `self.resultsdir` is where files will be saved to. Let me know if you still have an issue or close this with a comment.

**Comment by neelbasak08** [comment]
Thanks a lot Mr. Kristiansen. The problem resolved successfully. 
Regards
