### ISSUE TITLE
Download speed is slow

### ISSUE THREAD

**Issue by hufangd-2019** [trondkr/ERA5-ROMS#5]
Great code！But I had a  problem when I ran it: the download was too slow (20~100kb/s). I simply modified the code, now I can call Internet Download Manager (IDM) for multi-threaded download, the speed can reach 8mb/s. But the whole process of data download and processing is not elegant enough (need to run twice and comment out some statements). I wonder if the author has any plans to add a multi-threaded download module to the code. Thanks.

**Comment by trondkr** [comment]
Thats great. Feel free to submit a pull request and I'll include your improvements. T.
